[libdefaults]
  default_realm = EXAMPLE.COM
  dns_lookup_realm = false
  dns_lookup_kdc = false
  rdns = false
  ticket_lifetime = 24h
  renew_lifetime = 7d
  forwardable = true

[realms]
  EXAMPLE.COM = {
    kdc = kdc.hadoop.local
    admin_server = kdc.hadoop.local
  }

[domain_realm]
  .hadoop.local = EXAMPLE.COM
  hadoop.local = EXAMPLE.COM
